version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secretpassword'
    networks:
      - rabbit2neo4j
 q  neo4j:
    image: neo4j:4.1.4
    ports:
    - 7474:7474
    - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/secret
    networks:
    - rabbit2neo4j

networks:
  rabbit2neo4j:
    name: rabbit2neo4j